admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

mm_jamstorage:
    resource: "@MmJamstorageBundle/Resources/config/routing.yml"
    prefix:   /

