<?php

namespace Mm\JamstorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JamJarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JamJarRepository extends EntityRepository
{
}
